add DTDL v3 preview docs
Azure/opendigitaltwins-dtdl pull request #128
Opened 2022-03-09 16:52 UTC by jrdouceur

2022-03-10 22:40 UTC, rido-min requested changes
Summary of this PR review.
- Discuss how Properties are related to a physical device, or a Twin
- Clarify how some extensions can be used in v2
- Describe the "non-standard" adjunct-types
- Suggest to have the `@context` at the top of the files
- Add payload examples

2022-03-10 22:40 UTC, rido-min commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +When a Command request in a model is co-typed Optional, the service will assign the value of the `defaultValue` property to any Command request that does not explicitly specify a request value.
I dont understand which service would implement this extension.
ADT does not implement commands, and Hub HTTP Endpoint does not know the model.

2022-03-10 22:40 UTC, rido-min commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +If a service supports the QuantitativeTypes extension, and if the QuantitativeTypes context is specified, the service recognizes and understands the semantic types, unit types, and units itemized bel
I would add `Location` as an example of a semmantic type that does not require `unit`

2022-03-11 17:51 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +Telemetry describes the data emitted by any digital twin, whether the data is a regular stream of sensor readings or a computed stream of data, such as occupancy, or an occasional alert or informatio
I believe this document is using the term "digital twin" in a generic sense, which includes devices. (The language is called Digital Twin Definition Language, which implies that everything it describes is a digital twin.)

2022-03-11 17:55 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +| `name` | required | *string* | max 64 characters; must match this regular expression: `^[A-Za-z](?:[A-Za-z0-9_]*[A-Za-z0-9])?$`; must be unique for all contents in Interface | The programming name
Do you think it would be useful to describe the character set limits for name (here and in all name field descriptions) in text in the description field? I know we have the regular expression, but I think that many people don't easily read regular expressions. Perhaps some text like "The name is limited to alphanumeric characters and underscore and must start with a letter and may not end with an underscore."

2022-03-11 17:56 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +A Property describes the read-only and read/write state of any digital twin.
This language document does not provide documentation for any of our services, so I don't think we should refer to specific service behavior in this document. But ADT does support writable properties: you can PATCH a digital twin and update the property values.

2022-03-11 17:57 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +For example, the state of a digital twin might be written to by an application running in the cloud, but the digital twin itself is a device that only goes online once a day, so state information can
What's an "offline property"?

2022-03-11 17:59 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +### Property examples
This could be tricky for properties. I know we have a standard payload for the digital twin APIs but does Central also implement this payload? I seem to remember they do something different.

2022-03-11 18:00 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +A Command describes a function or operation that can be performed on any digital twin.
That's correct, but this language documentation is not documentation for our services. IMO, service-specific documentation should be in each service.

2022-03-11 18:01 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Property". |
I don't see where this documentation refers to co-types?

2022-03-11 18:04 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
I think we should include documentation like this with the parser because that's parser-specific behavior.

2022-03-11 18:10 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +### Array examples
Isn't there one just below?

2022-03-11 18:12 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +### Map examples
Isn't there one just below?

2022-03-11 18:26 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +IRIs in DTDL are [JSON-LD IRIs](https://w3c.github.io/json-ld-syntax/#iris) and may be relative or absolute.
I agree that we should describe that arbitrary co-types (and then arbitrary properties) can be applied to certain elements. I don't think it should be in this section. Perhaps it just needs a separate section?

2022-03-11 18:27 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +### Context
Do you mean the requirement that the dtmi:dtdl:context;3 is first in a list of contexts?

2022-03-11 18:28 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
But custom extensions are not allowed in DTDL v3.

2022-03-11 18:28 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
Should we link to the IoT Central partner extension in this documentation?

2022-03-11 18:56 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.Extensions.md
> +To use a feature extension, a model's `@context` property includes the extension's context specifier in addition to the DTDL context specifier, as illustrated in the example above.
I agree that we should have this documentation, but I think it should be in the main DTDL v3 docs, not here.

2022-03-11 19:03 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.historization.v1.md
> +        "dtmi:dtdl:context;2",
This extension is supported in DTDL v2 and v3, so I think it's nice to show an example using DTDL v2 to reinforce this.

2022-03-11 19:07 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "",
Can we remove the empty context items?

2022-03-11 19:08 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.historization.v1.md
> +| [Historization v1](./DTDL.historization.v1.md) | dtmi:dtdl:extension:historization;1 | [3](./DTDL.v3.md) |
The text near the top of this document says that this extension is supported in DTDL v2 and v3 but this table only lists DTDL v3.

2022-03-11 19:11 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +When a Command request in a model is co-typed Optional, the service will assign the value of the `defaultValue` property to any Command request that does not explicitly specify a request value.
This was added for Central.

2022-03-11 19:11 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +        "",
Can we remove the empty context element?

2022-03-11 19:12 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +| [Optionality v1](./DTDL.optionality.v1.md) | dtmi:dtdl:extension:optionality;1 | [3](./DTDL.v3.md) |
The text near the top of this document says this extension is usable in both DTDL v2 and v3, but this table only lists DTDL v3.

2022-03-11 19:18 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +If a service supports the QuantitativeTypes extension, and if the QuantitativeTypes context is specified, the service recognizes and understands the semantic types, unit types, and units itemized bel
I don't see Location in the list of quantitative types that are part of this extension.

2022-03-11 19:18 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +        "",
Can we remove the empty context item?

2022-03-11 19:20 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.layering.context.json
> +  "Layer": { "@id": "dtmi:dtdl:extension:layering:v1:Layer" }
Is the layer extension part of the preview? I didn't think we had approval for this one yet.

2022-03-11 19:21 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.om.context.json
> +{
I don't think this should be part of the preview, should it? I think this is part of the idea we have experimented with for linking to other ontologies.

2022-03-11 19:21 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.qudt.context.json
> +{
I don't think this should be part of the preview, should it? I think this is part of the idea we have experimented with for linking to other ontologies.

2022-03-11 19:22 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.schemaEncoding.context.json
> +{
Should this part of the preview? I don't think I know what the Encoded Boolean extension is?

2022-03-11 19:23 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.telemetryControl.context.json
> +{
Should this be part of the preview? I haven't seen these extensions before.

2022-03-11 19:26 UTC, briancr-ms requested changes
We need to resolve comments before merging.

2022-03-11 22:39 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.Extensions.md
> +        "",
Nope, that looks like a bug in the sample generator code.

2022-03-11 22:40 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.annotation.v1.md
> +Annotation is a DTDL language feature that enables a model to add custom metadata to a Property or a Telemetry.
Correct.

2022-03-11 22:43 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +When a Property or a Telemetry in a model is co-typed Historized, the service will persist the Historized Property or Telemetry values and make them available for querying and analytics.
Line 16 above says, "If a service supports the Historization extension...".  Do we need to repeat this just a few lines later?  I don't strongly object, but I want to be sure that we don't unintentionally make the doc overly verbose.

2022-03-11 22:45 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +        "dtmi:dtdl:context;2",
For the DTDL v3 preview docs, I manually removed some inappropriate references to v2, but I did not scour the whole set of documents to ensure that all v2 references are removed.  If you think this is important, I'll see how easy it would be to automate this.

2022-03-11 22:46 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +        "",
Nope, seems like another manifestation of that bug.

2022-03-11 22:48 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +| [Historization v1](./DTDL.historization.v1.md) | dtmi:dtdl:extension:historization;1 | [3](./DTDL.v3.md) |
Yes, the tables were one of the places I manually removed the v2 references because the auto-generated links were wrong.  Do you think this minor inconsistency is okay for preview docs?  If not, I'll figure out a workaround.

2022-03-11 22:49 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +The Initialized adjunct type can co-type a Property in DTDL version 2 or 3.
Clarification above in previous comment.  The answer to your second question is:  No, the GA parser does not understand these extensions.

2022-03-11 22:51 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
Is this part of the DTDL language or part of the service's implementation?  To my mind, it is the latter.  Different services could assign the initial value at times and in ways that are most appropriate for the service, which may differ from other services.

2022-03-11 22:51 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "dtmi:dtdl:context;2",
ditto above

2022-03-11 22:51 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "",
Yes, I'll look into this bug.

2022-03-11 22:51 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "dtmi:dtdl:context;2",
ditto above

2022-03-11 22:52 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +        "",
ditto above.

2022-03-11 22:53 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.optionality.v1.md
> +| [Optionality v1](./DTDL.optionality.v1.md) | dtmi:dtdl:extension:optionality;1 | [3](./DTDL.v3.md) |
Discussion above.

2022-03-11 22:54 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +If a service supports the QuantitativeTypes extension, and if the QuantitativeTypes context is specified, the service recognizes and understands the semantic types, unit types, and units itemized bel
Location is part of the IoT Central extension.  All Quantitative Types require a unit to be specified.

2022-03-11 22:54 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +        "",
ditto above

2022-03-11 22:54 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.historization.v1.md
> +| [Historization v1](./DTDL.historization.v1.md) | dtmi:dtdl:extension:historization;1 | [3](./DTDL.v3.md) |
I think it's fine to have this discrepancy for preview. I do think we should fix this for GA so that the text and the table are consistent.

2022-03-11 22:55 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +            "name": "setPointTemp",
sure

2022-03-11 22:56 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +    "@context": "dtmi:dtdl:context;3"
This style was copied from the current v2 docs.  Do we want to make this change everywhere?

2022-03-11 22:57 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +            "schema": "dtmi:azure:deviceManagement:DeviceInformation;2"
probably a typo

2022-03-11 23:00 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +The following Interface example shows how Interface inheritance can be used to create specialized Interfaces from more general Interfaces by inheriting the `contents` of the latter.
Yes, inheritance designates a subtype/supertype relation.  I believe ADT uses this for evaluating the validity of Relationship instances.  Do you want a description of this in the docs?  This is not a new thing with DTDL v3, and it was never mentioned in the v2 docs, but we could describe it (and, if so, I will confirm my understanding with someone from ADT).

2022-03-11 23:02 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +Telemetry describes the data emitted by any digital twin, whether the data is a regular stream of sensor readings or a computed stream of data, such as occupancy, or an occasional alert or informatio
This sentence was copied directly from the DTDL v2 doc:  https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#telemetry

2022-03-11 23:03 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `name` | required | *string* | max 64 characters; must match this regular expression: `^[A-Za-z](?:[A-Za-z0-9_]*[A-Za-z0-9])?$`; must be unique for all contents in Interface | The programming name
The content of cells in this table are automatically generated from the metamodel.  I can perhaps write a language-generation module that would generate readable prose descriptions from a restricted subset of regular expressions, but I recommend deprioritizing this relative to getting the DTDL v3 preview docs published.

2022-03-11 23:05 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +A Property describes the read-only and read/write state of any digital twin.
This sentence was copied directly from the DTDL v2 doc: https://github.com/Azure/opendigitaltwins-dtdl/blob/master/DTDL/v2/dtdlv2.md#property

2022-03-11 23:06 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Property". |
Before we removed all co-types from the v3 standard extensions, this table did include co-types.  But they are no longer part of DTDL v3, only part of various language extensions.

2022-03-11 23:09 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +| [Historization v1](./DTDL.historization.v1.md) | dtmi:dtdl:extension:historization;1 | [3](./DTDL.v3.md) |
The fix will be zero effort.  It will be fixed by not manually removing the v2 references from the generated docs. :)

2022-03-11 23:43 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `target` | optional | [DTMI](#digital-twin-model-identifier) | max 2048 characters; must match this regular expression: `^dtmi:[A-Za-z](?:[A-Za-z0-9_]*[A-Za-z0-9])?(?::[A-Za-z](?:[A-Za-z0-9_]*[A-Za
See my comment above about regex descriptions.

2022-03-11 23:43 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Relationship". |
discussion above

2022-03-11 23:45 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
An alternative note that might be worth mentioning is that the "target" of a Relationship is a non-requisite reference, unlike the "schema" of a Component.  This is the language-pertinent aspect of the parser behavior that Rido describes.

2022-03-11 23:49 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Array examples
Yes, in fact all of the complex schema types have payload examples.

2022-03-11 23:53 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +For a full definition of DTMI, please see the [DTMI repo on GitHub](https://github.com/Azure/digital-twin-model-identifier).
I think we probably can, as long as any references are updated appropriately.

2022-03-11 23:54 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Context
Indeed, this requirement should be stated in this doc.

2022-03-11 23:58 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
Technically, custom extensions are not an aspect of the DTDL language, but rather an aspect of the service, tool, library, or environment that processes models written in the DTDL language.  The language allows extensions, and it says nothing about how these extensions get created, stored, imported, or exported.  The current GA parser implements only the extensions that are built into it when the assembly is generated.  The current preview parser has an undocumented API for loading additional extensions.  But none of this really relates to the DTDL language version.

2022-03-12 00:01 UTC, jrdouceur commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.om.context.json
> +{
Okay, I clearly made a config mistake when generating these.  This should not be included, either.

2022-03-12 00:01 UTC, jrdouceur commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.qudt.context.json
> +{
yep, config mistake on my part

2022-03-12 00:02 UTC, jrdouceur commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.schemaEncoding.context.json
> +{
oh my.  I really screwed up the config badly.

2022-03-12 00:11 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
Good question. I did not find something in the Central docs with a quick search. Should we get Central to write something for their extension?

I would not hold up the merge of this PR or releasing this preview for this.

2022-03-12 00:53 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "",
Well, this is fascinating.  What value would you expect the variable `strings` to have after the following statement?
```
string[] strings = string.Empty.Split(new char[] { ' ' });
```
I would have expected it to be an empty array.  But no.  It is an array containing a single element that is the empty string.  To get the behavior I had expected, you have to specify `StringSplitOptions.RemoveEmptyEntries`.

2022-03-12 01:01 UTC, jrdouceur commented on DTDL/v3-preview/context/DTDL.v1.FeatureExtension.om.context.json
> +{
Turns out this was not a config bug.  This is detritus left over from a previous execution.  The generated doc folder is not cleaned before building.  I will correct this.

2022-03-12 01:45 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +        "",
Yeah, I tend to agree with you. It always fun to find an unexpected corner case!

2022-03-14 14:26 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +    "@context": "dtmi:dtdl:context;3"
I'd like to. 

I believe we discussed this when reviewing the linter proposal and we agreed that having the @context at the top will help with readability.

2022-03-14 14:31 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +            "schema": "dtmi:azure:deviceManagement:DeviceInformation;2"
fixed

2022-03-14 14:32 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
added

2022-03-14 14:32 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Property". |
Added a new subsection below.

2022-03-14 14:34 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +The following Interface example shows how Interface inheritance can be used to create specialized Interfaces from more general Interfaces by inheriting the `contents` of the latter.
I think will be great !!.  I think we should try to be as explicit as possible to describe the inheritance feature, for now we have contents and relationships, but no schemas.. anything else?

2022-03-14 14:38 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +IRIs in DTDL are [JSON-LD IRIs](https://w3c.github.io/json-ld-syntax/#iris) and may be relative or absolute.
Added a new subsection below.

2022-03-14 14:43 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +For example, the state of a digital twin might be written to by an application running in the cloud, but the digital twin itself is a device that only goes online once a day, so state information can
properties that are reflected in the twin, hence can be readed/updated when the device is offline

2022-03-14 14:45 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.historization.v1.md
> +        "dtmi:dtdl:context;2",
For this second iteration, instead of manually removing the v2 references, I updated the links so they point to the actual DTDL v2 docs.  This should eliminate all of these inconsistencies.

2022-03-14 14:47 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
>When JSON is used to serialize Telemetry data

Are other formats (non JSON) supported in the payload?

2022-03-14 14:48 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `name` | required | *string* | max 64 characters; must match this regular expression: `^[A-Za-z](?:[A-Za-z0-9_]*[A-Za-z0-9])?$`; must be unique for all contents in Interface | The programming name
I looked into this a bit, and I think language-generation would be hard, especially since the generation code is internationalized.  Instead, I propose adding to the metamodel format a new property, "dtmm:patternDesc", which will be a language map of descriptions of a sibling "sh:pattern" constraint.  For now, I just manually edited the generated doc to replace the regexes in the tables with descriptive text.

2022-03-14 14:52 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Property". |
Are there any rules for "co-types" names? (reserved words, max-lenght, inheritance implications). 

I've seen services making "special" use of this feature w/o any extension. Should we have a doc (not this spec) to document those?

Can they be applied to any DTDL element?

2022-03-14 15:01 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +    "@context": "dtmi:dtdl:context;3"
If @briancr-ms agrees, I'll make this change.

2022-03-14 15:03 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +            "name": "setPointTemp",
I didn't realize we had released any canonical samples.  Can you post a link?  I suspect there are other cases in which I should be using these, as well.

2022-03-14 15:06 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
> custom extensions are not an aspect of the DTDL language,

how should we define the central context ? maybe it's not the right wording.. we should be more explicit explaining that "the language" allows some customizations by adding addtional "context"

2022-03-14 15:06 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +The following Interface example shows how Interface inheritance can be used to create specialized Interfaces from more general Interfaces by inheriting the `contents` of the latter.
The only property whose values are imported is "contents".  I can add some prose to describe the subtype/supertype relation, but I think we should shy away from describing service-specific behavior such as how ADT uses this relation in assessing target validity.

Incidentally, when you write, "contents and relationships", this is just contents.  Relationship is just another Content type, along with Property, Telemetry, Command, and Component.

2022-03-14 15:08 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
The DTDL does not specify how payloads are encoded.  At present, the only implementations we have use JSON, but there have been discussions of supporting other formats.

2022-03-14 15:08 UTC, rido-min commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
not the language, rather the extension iteself. 

I'm having problems trying to understand which service (and how) will implement this extension.

2022-03-14 15:13 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +| `@type` | required | [IRI](#internationalized-resource-identifier) |  | This must be "Property". |
A co-type is either an IRI or a JSON-LD term; I can state this in the doc.  Yes, undefined types can be applied to any DTDL element.

Regarding reserved words, this is exactly the issue you ran into the other day with the term "model".  I need to think a bit more about what to do about these.  I hope we can avoid conditioning the DTDL v3 preview docs on this.

2022-03-14 15:20 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
I think this is a fundamental disagreement in interpretation.  To my mind, some aspects of the parser have nothing to do with the language, such as whether it implements a callback to resolve identifiers versus requiring all definitions to be provided a priori; a language-compliant parser could do either of these.  The parser and the language spec must agree on whether a model is valid, of course.

2022-03-14 15:30 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Property examples
Perhaps the question here is:  Is there a DTDL standard for the JSON encoding of a Property payload?  If so, I think it can go in this doc.

2022-03-14 15:32 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
Isn't this information that belongs in the documentation for the service?  The extension doesn't specify which services support it.

2022-03-14 15:34 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +If a service supports the QuantitativeTypes extension, and if the QuantitativeTypes context is specified, the service recognizes and understands the semantic types, unit types, and units itemized bel
There is a discussion below about this.  So far, it seems that none of us is aware of any docs describing the Central extension.  See the comment thread beginning with Brian's comment, "Should we link to the IoT Central partner extension in this documentation?"

2022-03-14 15:46 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.Extensions.md
> +To use a feature extension, a model's `@context` property includes the extension's context specifier in addition to the DTDL context specifier, as illustrated in the example above.
I believe Brian is referring to file DTDL.v3.md, in contrast to the current file, which is DTDL.Extensions.md.

2022-03-14 15:55 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
Oh, I think I misinterpreted "custom extensions" to mean "dynamic extensions".

2022-03-14 15:57 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +            "name": "setPointTemp",
https://docs.microsoft.com/en-us/azure/iot-develop/concepts-modeling-guide

2022-03-14 15:58 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +The following Interface example shows how Interface inheritance can be used to create specialized Interfaces from more general Interfaces by inheriting the `contents` of the latter.
fair, although I still think that an example will help to clarify

2022-03-14 15:59 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
> When JSON is used

.. implies there are other supported formats

2022-03-14 16:06 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +Telemetry describes the data emitted by any digital twin, whether the data is a regular stream of sensor readings or a computed stream of data, such as occupancy, or an occasional alert or informatio
I believe this document is attempting to use the term "digital twin" to refer to anything that can be described with the Digital Twin Definition Language as a digital twin. The Introduction section in this document attempts to list what's covered by the term "digital twin".

Any digital twin can produce telemetry. ADT provides a REST API that can be used to send telemetry on behalf of a digital twin: https://docs.microsoft.com/en-us/rest/api/digital-twins/dataplane/twins/digitaltwins_sendtelemetry.

2022-03-14 16:07 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +## Feature extensions
Added a note regarding additional context specifiers.

2022-03-14 16:09 UTC, jrdouceur commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
It just implies that there *might* be other supported formats.  I would not want this doc to imply the opposite, that no other serialization can be supported and still be DTDL v3 compliant.

2022-03-14 16:11 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +For example, the state of a digital twin might be written to by an application running in the cloud, but the digital twin itself is a device that only goes online once a day, so state information can
That sounds like a service-specific feature. DTDL does not describe online or offline properties. For example, PnP already implements "offline properties" while ADT does not.

Separate from DTDL, we have an API pattern that's used for synchronizing state between potentially disconnected digital twin clients and servers. That's the ackCode, etc. stuff.

2022-03-14 16:19 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
I agree with JD, this is not parser documentation. A parser may not implement a callback at all.

We should document the parser separately.

2022-03-15 00:10 UTC, rido-min commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +The Initialized adjunct type can co-type a Property in DTDL version 2 or 3.
I'm having some issues claiming that the extension can be used in v2 if the "canonical paser" does not support it.

2022-03-15 00:10 UTC, rido-min commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
sure, the service docs should explain, I was asking for an example to help explaining the feature. Eg. will Central create the default values on device provisioning?

2022-03-15 00:10 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +### Telemetry examples
how? can users use CBOR or Protobuff? how a service will validate the expected payloads?

2022-03-15 00:10 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +A Property describes the read-only and read/write state of any digital twin.
I dont think we should use the v2 spec as a baseline, if I see an opportunity to improve the spec, why not proposing it?

2022-03-15 00:10 UTC, rido-min commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
this is not about the parser rather what makes a valid model. AFAIK I can define relationships with undefined dtmi as targets

2022-03-15 14:59 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
I agree with JD that this documentation should not provide documentation for our services--the service teams need to own that documentation.

I don't think we know whether or not Central will act on the initialValue property--it's optional for services to support extensions and they may support it at some point after this documentation is complete.

2022-03-15 16:13 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.v3.md
> +A Relationship is different from a [Component](#component) because it describes a link to a separate digital twin.
I see what you're saying: the DTMI in the target property is a reference DTMI and therefore does not have to have a definition.

2022-03-15 16:36 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
For me, the description in this doc makes sense: "the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is created." That is, when the instance is created in the service, the service will assign the initial value.

But there must be something more you're looking for. Can you give an example of what would help?

2022-03-16 22:58 UTC, rido-min commented on DTDL/v3-preview/DTDL.quantitativeTypes.v1.md
> +```
can we add an example to show how to use Semantic types to object fields?
eg
```json
 {
        "@type": "Property",
        "name": "myEvents",
        "schema": {
          "@type": "Array",
          "elementSchema": {
            "@type": "Object",
            "fields": [
              {
                "@type" : ["Field", "Temperature"],
                "name": "temp",
                "schema": "double",
                "unit" : "kelvin"
              }
            ]
          }
        }
      }
```

2022-03-17 16:42 UTC, rido-min commented on DTDL/v3-preview/context/DTDL.v3.iotcentral.context.json
> +{
Any reason to do not include these semantic types in the quatitativeTypes extension? 

If we decide to ship these, they should also have the corresponding markdown.

2022-03-17 17:09 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v3.iotcentral.context.json
> +{
We already have Acceleration and Velocity in the quantitative types. State, Event, and Location are not quantitative types so I don't think they should be in that extension.

2022-03-21 17:28 UTC, rido-min commented on DTDL/v3-preview/DTDL.initialization.v1.md
> +When a Property in a model is co-typed Initialized, the service will assign the value of the `initialValue` property to each instance of the Property in the service at the time the instance is create
I will add an example once we publish this extension

2022-03-21 18:09 UTC, briancr-ms commented on DTDL/v3-preview/DTDL.Extensions.md
> +## Available feature extensions
I think they just keep using the Central extension.

2022-03-21 18:16 UTC, briancr-ms commented on DTDL/v3-preview/context/DTDL.v3.iotcentral.context.json
> +{
It seems to me that if we want to create a new feature extension for State, Event, and Location, then we should create a v-team and go through that process to do this. I don't think we should decide to create a new feature extension in this discussion.

2022-03-21 18:17 UTC, briancr-ms approved these changes

2022-03-24 00:04 UTC, closed without merging